### PR TITLE
Reviewed the ACMG classification pipeline and edited tape code errors

### PR DESCRIPTION
**Pull request by cipherome-yoomi**

### CODE REVIEW

**Review by cipherome-sam — CHANGES_REQUESTED** [review]

**Comment by cipherome-yoomi** [comment]
> 
Yes, the email you attached is relevant to this issue. 
The main problem is that the "stop" information from rek_dict is not updated properly.
When a KeyError is raised, the stop information should be updated to None, but this code uses the stop information from the previous gene of which stop information is available in rek_dict.

**Comment by cipherome-sam** [comment]
To capture multiple exceptions, you can use the following. 
```
except (UnboundLocalError, KeyError) as error:
```

**Comment by cipherome-yoomi** [comment]
This still doesn't update the "stop" info...
I've updated the code with the line that captures the multiple exceptions as you suggested!

**Comment by cipherome-sam** [comment]
> 

Yes, the merge should be stopped until I finally approve it. :-)

**Review by cipherome-sam — APPROVED** [review]
PR is done. Please merge.

**Comment by cipherome-yoomi** [comment]
Did I merge?..... I'm still learning github....😭 Thanks for the review!!!

**Pull request merged**
